// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListTransactions() {
  return window['go']['main']['App']['ListTransactions']();
}

export function PostTransaction(arg1) {
  return window['go']['main']['App']['PostTransaction'](arg1);
}
