// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTransaction(arg1:main.Transaction):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListTransactions():Promise<Array<main.Transaction>>;

export function PostTransaction(arg1:main.Transaction):Promise<void>;
